# Generated by hand for the BallsDex crafting package.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [("bd_models", "0019_special_animation_support")]

    operations = [
        migrations.CreateModel(
            name="CraftingRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "result",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="crafted_by", to="bd_models.ball"),
                ),
            ],
            options={"db_table": "craftingrecipe"},
        ),
        migrations.CreateModel(
            name="CraftingIngredientGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("label", models.CharField(blank=True, max_length=64)),
                ("minimum_choices", models.PositiveIntegerField(default=1)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_groups",
                        to="crafting_pkg.craftingrecipe",
                    ),
                ),
            ],
            options={"db_table": "craftingingredientgroup"},
        ),
        migrations.CreateModel(
            name="CraftingIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                ("amount", models.PositiveIntegerField(default=1)),
                (
                    "ingredient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bd_models.ball"),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="crafting_pkg.craftingrecipe",
                    ),
                ),
            ],
            options={
                "db_table": "craftingingredient",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recipe", "ingredient"), name="craftingingredient_unique"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CraftingGroupOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "ball",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="bd_models.ball"),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="crafting_pkg.craftingingredientgroup",
                    ),
                ),
            ],
            options={
                "db_table": "craftinggroupoption",
                "constraints": [
                    models.UniqueConstraint(fields=("group", "ball"), name="craftinggroupoption_unique"),
                ],
            },
        ),
    ]

